# Generated by Django 4.0 on 2022-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('roll_number', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
    ]
